# Remember to export a AWS_PROFILE environment variable before running this

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-udacity-capstone-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
#    instanceType: t2.small
#    desiredCapacity: 3
    minSize: 1
    maxSize: 3
    instancesDistribution:
      maxPrice: .2
      instanceTypes: ["t2.small", "t3.small"]
      onDemandPercentageAboveBaseCapacity: 10
    ssh:
      publicKeyName: eks-capstone
