apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-master
  labels:
    app: backend-python
spec:
  selector:
    matchLabels:
      app: backend
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: hungtruongquoc/udacity-devops:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: backend-master
  labels:
    app: backend
    role: master
    tier: backend
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    app: backend
    role: master
    tier: backend